### PR TITLE
Correct the license to be accurate

### PR DESCRIPTION
**Pull request by cdeszaq**
We had the "pointer" piece, but not the _actual_ license, which we need.

### CODE REVIEW

**Comment by archolewa** [comment]
I'm assuming you copy-pasted this from some apache license website or other?

**Comment by cdeszaq** [comment]
@archolewa I grabbed it from GitHub's little helper tool that recognizes when you're trying to add a file like "LICENSE" through the web-ui, and it gives a little dropdown with licenses you can add.

**Comment by archolewa** [comment]
👍

**Comment by michael-mclawhorn** [comment]
👍

**Pull request merged**
