### PR TITLE
duplicate dependency declaration is removed in order to eliminate maven build warnings

### PR DESCRIPTION
**Pull request by dejan2609**
_**Related ticket**_: #456

_**Status:**_ `Reviewable`

### CODE REVIEW

**Comment by QubitPi** [comment]
I don't think this is right. The two are needed. Consider closing.

**Comment by QubitPi** [comment]
I don't think this is right. We'll need both.

**Comment by dejan2609** [comment]
@QubitPi: just out of curiosity: why do you need two _**identical**_ declarations of **com.yahoo.fili:fili-core**  (in fili-security/pom.xml) ? It does look kind of strange.

```
    <dependencies>
        <dependency>
            <groupId>com.yahoo.fili</groupId>
            <artifactId>fili-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yahoo.fili</groupId>
            <artifactId>fili-core</artifactId>
            <type>test-jar</type>
        </dependency>
        <dependency>
            <groupId>com.yahoo.fili</groupId>
            <artifactId>fili-core</artifactId>
        </dependency>
    </dependencies>
```

**Comment by dejan2609** [comment]
Update: ***fili-security*** effective pom for both related branches (yahoo:master and this PR) shows identical list of (effective) dependencies, see below. 

It's obvious that second **com.yahoo.fili:fili-core:jar** declaration (in ***fili-security/pom.xml***) is redundant (hence this simple PR is created).
 
@QubitPi : please remove `BREAKING CHANGE` label. 

```
<dependencies>
    <dependency>
      <groupId>com.yahoo.fili</groupId>
      <artifactId>fili-core</artifactId>
      <version>0.9-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.yahoo.fili</groupId>
      <artifactId>fili-core</artifactId>
      <version>0.9-SNAPSHOT</version>
      <type>test-jar</type>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.0-groovy-2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cglib</groupId>
      <artifactId>cglib-nodep</artifactId>
      <version>3.2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.objenesis</groupId>
      <artifactId>objenesis</artifactId>
      <version>2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-all</artifactId>
      <version>1.3</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>1.1.0.Final</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.25</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

**Pull request merged**
