### PR TITLE
Add <p> tags for cdeszaq

### PR DESCRIPTION
**Pull request by jacobtolar**
😈

### CODE REVIEW

**Comment by jacobtolar** [comment]
Since I had the script to fix up my changes in #107 I figured I might as well run it on everything.

The simple bash version I used on #107 - 
```
find . \( -name '*.java' -o -name '*.groovy' \)  -exec gsed -i 's/^\(\s*\)\*\s*$/\1* <p>/g' {} \;
```

Slightly better version that I used here which updates only comments that look like javadocs (probably not perfect, but seems to be sufficient):

https://gist.github.com/jacobtolar/46f03ced47ce6f15c005e8201ba601e1

**Comment by cdeszaq** [comment]
So, one interesting note for this: It's not _all_ whitespace in JavaDoc that needs this, only vertical whitespace _contained in_ the description section that needs it. So, this means that there _should_ be a blank line before the `@params` block, as well as between any other `@blah` sections (like `@returns`, for example).

**Comment by jacobtolar** [comment]
This is what I get for not reading the javadocs for javadoc. :)

**Comment by jacobtolar** [comment]
Updated to a significantly smaller changeset -- made a few small changes to the script and then manually staged the valid changes.

**Comment by jacobtolar** [comment]
And -- right, that would be nice, although this particular script would need to be a bit smarter. e.g., it would add `<p>` tags inside of `<pre>` blocks, which isn't what you want. Don't think it would be too difficult to make the necessary changes, though.

**Comment by cdeszaq** [comment]
Merging. These are Javadoc-only changes, and trivial cleanup ones at that.

**Pull request merged**
