### PR TITLE
Translate top README to Chinese

### PR DESCRIPTION
**Pull request by QubitPi**

### CODE REVIEW

**Comment by kevinhinterlong** [comment]
Do we want to have a `translations` folder or just keep it in the root?

**Comment by michael-mclawhorn** [comment]
It might make sense to put alternate languages in subdirectories by their i18n locale.
http://www.oracle.com/technetwork/java/javase/java8locales-2095355.html
That way any additional translations can be checked for and routed programmatically as contributions arise.

**Comment by cdeszaq** [comment]
To facilitate deeper discussion with a broader audience, I've created [a topic in the Developer's group](https://groups.google.com/forum/#!topic/fili-developers/7wFhLBb8mwg).

**Comment by saiyan86** [comment]
Very good translation. Keep up the good work!

**Comment by michael-mclawhorn** [comment]
What's the relationship between this PR and https://github.com/yahoo/fili/pull/398 ?

**Comment by QubitPi** [comment]
@michael-mclawhorn I think, instead of having a markdown README, @saiyan86 wants a [org-mode](https://en.wikipedia.org/wiki/Org-mode) README, which can be automatically translated to HTML. I know @saiyan86 is a big fan of Emacs org-mode.

So the relationship is that this PR is a standard README translation, whereas https://github.com/yahoo/fili/pull/398 tries to transform README from markdown file to Emacs org-mode file.

But I'm not sure this is the way that core team wants.

**Comment by saiyan86** [comment]
Actually it's a org-mode source file which can be exported to markdown. It is totally OK for me if you guys don't want that. I have reviewed this PR. The translation is very good.

**Comment by QubitPi** [comment]
Duplicate of https://github.com/yahoo/fili/pull/444

**Pull request closed without merging**
