### PR TITLE
Filter improvements

### PR DESCRIPTION
**Pull request by will-lauer**
- threading extraction function through all supported filters
- switching to InFilter instead of an OR of multiple selectors

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by cdeszaq** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/builders/ConsolidatingDruidFilterBuilder.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Fili/fili/pullRequest?prid=5053235&bid=16635971)

**Comment by cdeszaq** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/builders/ConsolidatingDruidFilterBuilder.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Fili/fili/pullRequest?prid=5053235&bid=16635971)

**Comment by cdeszaq** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ fili-core/src/main/java/com/yahoo/bard/webservice/druid/model/builders/ConsolidatingDruidFilterBuilder.java  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Fili/fili/pullRequest?prid=5053235&bid=16635971)

**Comment by will-lauer** [comment]
There is a bug in DruidInFilterBuilder where it doesn't handle the NoopSearchProvider correctly, causing some legal filters to be processed incorrectly. This is causing unit test failures in SingleDimensionNoRowsFilterDataServletSpec and NoMetricsSingleDimensionDataServletSpec.

**Pull request closed without merging**
