### PR TITLE
Lift required override on deprecated method in MetricLoader

### PR DESCRIPTION
**Pull request by QubitPi**
Address issue https://github.com/yahoo/fili/issues/608

### CODE REVIEW

**Comment by archolewa** [comment]
I'm a little late to the party, but I think it's a really bad idea to "deprecate" a method and then have it throw an unsupported operation exception. If a method now makes *such little sense* that we can't support it, then we should just delete it. All else being equal, compile errors >>>>>>> runtime errors. 

Especially since this is a trivially easy thing to fix for people using the old method: add an extra parameter to the method signature. The implementation doesn't need to be touched at all.

**Comment by archolewa** [comment]
*Especially* since the other implementation is a default!

Which means that if someone adds a new interface, their class will compile, and then explode at runtime by default.

**Comment by archolewa** [comment]
Frankly, I think we should just make the "new" method no longer default and delete the old method if we don't want to make people provide an implementation of the deprecated method.

**Comment by QubitPi** [comment]
According to doc, deprecated method can only be removed after a new release.

I'm OK if you open a new PR or roll back this.

**Comment by archolewa** [comment]
Eh, I don't think I care enough to go reverting code. This is fairly minor, and our codebase isn't widely used.

I do think we should clean this up for the next minor rev though, which we're probably past due for (current version: 0.9.118).

**Pull request merged**
